### PR TITLE
improved success requests

### PR DESCRIPTION
**Pull request by destebanm**
The problem was when a response returns HTTP status code 200 but responseText was empty (some services returns this kind of reponse).  Now, with this code, this kind of response executes fires the success callback.

### CODE REVIEW

**Comment by inorganik** [comment]
Hmm - indentation is a bit borked. You have almost as many additions as deletions - in other words, you've replaced the whole file, which makes it very hard to read diffs. Can you please re-submit so that the only diffs are where your edits have been made?

**Comment by inorganik** [comment]
still the whole file is changed 😬

**Comment by destebanm** [comment]
So sorry,is the first time that i do a pull request :grimacing: Give me another try!

**Comment by inorganik** [comment]
that's ok. Just make a temp copy of your file, then do a `git rebase master` and make your edits again. then push and make a new PR.

**Pull request closed without merging**
